### ISSUE TITLE
在背景图上画图，类似于在车库cad图上画车位

### ISSUE THREAD

**Issue by toKnowMore** [lanniu/vue-mxgraph-example#9]

**Comment by lanniu** [comment]
OK

**Comment by lanniu** [comment]
手动画矩形：https://github.com/lanniu/vue-mxgraph-example/commit/9782f40736f7f64c542dcddcf18da4a910eaccd9

[在线预览](https://lanniu.github.io/vue-mxgraph-example/dist/#/manualDrawing)
